dbfilename redis_queue.rdb
dir /home/ninah/Eval/erp/ERPNext-me/erp-git/frappe/config/pids
pidfile /home/ninah/Eval/erp/ERPNext-me/erp-git/frappe/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/ninah/Eval/erp/ERPNext-me/erp-git/frappe/config/redis_queue.acl
